version: '3.8'

services:
  ### MySQL Container
  mysql:
    container_name: mysql
    build:
      context: ./db

    ports:
      - "3306:3306"
    networks:
      - network1
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      DATABASE_PORT: 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    networks:
      - network1
    depends_on:
      mysql:
        condition: service_healthy

networks:
  network1:
    name: se-methods
    driver: bridge
