name: Docker compose test
on:
  push:
    branches:
      - develop

jobs:
  unitTests:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Unit tests
        run: mvn -Dtest=com.napier.sem.AppTest test
      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/site/jacoco
          flags: Unit Tests
          verbose: true
          slug: Drakon4ik-Coder/SET08103_GP
          
  integrationTests:
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Integration Tests
        run: |
          docker build -t database ./db 
          docker run -d --name database -p 3306:3306 -e MYSQL_DATABASE=db -e MYSQL_USER=user -e MYSQL_PASSWORD=1234 -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_ROOT_HOST='%' -v world.sql:/etc/mysql/ database
          mvn -Dtest=com.napier.sem.IntegrationTests test
          docker stop database
          docker rm database
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/site/jacoco
          flags: Integration Tests
          verbose: true
          slug: Drakon4ik-Coder/SET08103_GP

  build:
    name: Docker compose test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
