name: Master workflow
on:
  push:
    branches:
      - master

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # now required for public repos
          directory: ./target/site/jacoco
          flags: Unit Tests # optional
          verbose: true # optional (default = false)
          slug: Drakon4ik-Coder/SET08103_GP

  integrationTests:
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Integration Tests
        run: |
          docker build -t database ./db 
          docker run -d --name database -p 3306:3306 -e MYSQL_DATABASE=db -e MYSQL_USER=user -e MYSQL_PASSWORD=1234 -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_ROOT_HOST='%' -v world.sql:/etc/mysql/ database
          mvn -Dtest=com.napier.sem.IntegrationTests test
          docker stop database
          docker rm database
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/site/jacoco
          flags: Integration Tests
          verbose: true
          slug: Drakon4ik-Coder/SET08103_GP

  build:
    name: Build Run in Docker and Deploy Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package and Run docker compose
        run: |
            mvn package -DskipTests
#            docker-compose up --abort-on-container-exit
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            automatic_release_tag: "latest"
            files: |
              ./target/*.jar

  publish_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) MySQL container
        id: meta1
        uses: docker/metadata-action@2133b8fefb4f46108ea2a0a600ac76277714dbd9b2f82c1db05fa7ab7e74bd58
        with:
          images: drakon4ikcoder/set08103_db

      - name: Build and push MySQL container
        run: |
          docker build -t drakon4ikcoder/set08103_db -f db/Dockerfile .
          docker push drakon4ikcoder/set08103_db

      - name: Extract metadata (tags, labels) App container
        id: meta2
        uses: docker/metadata-action@9c4d0143dc236f4f8f6d83019892f78fc3cef368a55be56152a4ac0d37ed01d0
        with:
          images: drakon4ikcoder/set08103_app

      - name: Build and push App container
        run: |
          docker build -t drakon4ikcoder/set08103_app .
          docker push drakon4ikcoder/set08103_app