name: Develop workflow
on:
  push:
    branches:
      - develop

jobs:
  integrationTests:
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Integration Tests
        run: |
          docker build -t database ./db 
          docker run -d --name database -p 3306:3306 -e MYSQL_DATABASE=db -e MYSQL_USER=user -e MYSQL_PASSWORD=1234 -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_ROOT_HOST='%' -v world.sql:/etc/mysql/ database
          mvn -Dtest=com.napier.sem.IntegrationTests test
          docker stop database
          docker rm database
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/site/jacoco
          flags: Integration Tests
          verbose: true
          slug: Drakon4ik-Coder/SET08103_GP

  unitTests:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Unit tests
        run: mvn -Dtest=com.napier.sem.AppTest test

  build:
    name: Build Run in Docker and Deploy Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
        run: |
          exit_code=$(docker wait app)
          if [ $exit_code -ne 0 ]; then
            exit 1
          fi
      - name: View mysql logs
        run: docker-compose -f docker-compose.yml logs mysql
      - name: View app container logs
        run: docker-compose -f docker-compose.yml logs app