name: Docker compose test
on: push

jobs:
  build:
    name: Docker compose test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Maven tests
        run: mvn test
      - name: Compose Docker services
        run: docker-compose -f docker-compose.yml build
      - name: Run services
        run: docker-compose -f docker-compose.yml up -d
      - name: Check exit code
        run: |
          exit_code=$(docker wait app)
          if [ $exit_code -ne 0 ]; then
            exit 1
          fi
      - name: View mysql logs
        run: docker-compose -f docker-compose.yml logs mysql
      - name: View app container logs
        run: docker-compose -f docker-compose.yml logs app